version: '3'
services:
  nginx:
    image: danreynolds/summonerexpert_client:$DEPLOY_TAG
    ports:
      - 80
    networks:
      default:
      nginx_default:
        aliases:
          - SUMMONEREXPERT_CLIENT
    volumes:
      - logs:/etc/nginx/log/
      - ./nginx.upstream.conf:/etc/nginx/conf.d/default.conf
      - ./.env:/app/.env
    environment:
      - ENV_KEY=$ENV_KEY
      - DEPLOY_TAG=$DEPLOY_TAG
    env_file:
      - .env
volumes:
  logs:
networks:
  nginx_default:
    external: true
