FROM starefossen/ruby-node:2-8

# Set the working directory to /app
RUN mkdir /app
WORKDIR /app

# Add Ruby dependencies necessary for deployment
RUN gem install sshkit rake

# Add a static asset server for running production build
RUN npm install -g serve

# Copy the current directory contents into the container at /app
ADD . /app
