version: '3'
services:
  app:
    command: 'serve -s build -p 3000'
    image: danreynolds/summonerexpert_client:$DEPLOY_TAG
    ports:
      - 3000
    volumes:
      - ./.env:/app/.env
    environment:
      - ENV_KEY=$ENV_KEY
      - DEPLOY_TAG=$DEPLOY_TAG
    env_file:
      - .env
  nginx:
    image: nginx
    depends_on:
      - app
    ports:
      - 80
    networks:
      default:
      nginx_default:
        aliases:
          - SUMMONEREXPERT_CLIENT
    volumes:
      - logs:/etc/nginx/log/
      - ./nginx.upstream.conf:/etc/nginx/conf.d/default.conf
volumes:
  logs:
networks:
  nginx_default:
    external: true
